### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by jeremygiberson** [FormidableLabs/gui4comby#7]
The user should be able to select from a list of light and dark themes in the settings tab to suit their own sense of aesthetics. 

We are currently using the script `scripts/vsthemes2bootstrap.js` to iterate .json files in the themes folder and generate a css file w/ bootstrap variable overrides. Additionally, it will need to generate css overrides for ace-editor syntax highlight themeing. It's very much in proof of concept mode, with a non-exhaustive mapping of theme colors to app styling. 

It's worth revisiting whether we want to attempt to map the theme to bootstrap styling overrides, or instead generate a set of classes for app styling and simply apply those classes to UI elements.

Ideally, I'd like to support any theme found in https://vscodethemes.com/. https://vscodethemes.com/ is an open source site that curates the themes available in the vscode marketplace and allows users to peruse the available vs code themes. It works by crawling the marketplace search api and extracting information from manifest files. 

Notes from initial research into this process

### vscode theme integration
1. query marketplace for themes
```
POST https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery HTTP/1.1
content-type: application/json
accept: application/json;api-version=3.0-preview.1
accept-encoding: gzip

{
  filters: [
    {
      criteria: [
        {
          filterType: 8, 
          value: "Microsoft.VisualStudio.Code"
        },
        {
          filterType: 10,
          value: "theme"
        }
      ],
      pageNumber: 1,
      pageSize: 100,
      sortBy: 0,
      sortOrder: 0
    }
  ],
  assetTypes: [],
  flags: 0
}
```

2. Locate the url of the manifest files from the search results
```json
{   
    "versions": [
        {
            "files": [
                {
                    "assetType": "Microsoft.VisualStudio.Code.Manifest",
                    "source": "https://tal7aouy.gallerycdn.vsassets.io/extensions/tal7aouy/theme/2.4.0/1658665564745/Microsoft.VisualStudio.Code.Manifest"
                }               
            ],
            "assetUri": "https://tal7aouy.gallerycdn.vsassets.io/extensions/tal7aouy/theme/2.4.0/1658665564745",
        }
    ],
}
```

3. Retrieve the contents of the manifest file
```
GET https://tal7aouy.gallerycdn.vsassets.io/extensions/tal7aouy/theme/2.4.0/1658665564745/Microsoft.VisualStudio.Code.Manifest
```

4. Find and extract theme files with a json extension
```json
{
  "contributes": {
    "themes": [
      {
        "label": "Theme",
        "uiTheme": "vs-dark",
        "path": "./themes/Theme.json"
      },
      {
        "label": "Theme (Italic)",
        "uiTheme": "vs-dark",
        "path": "./themes/Theme(Italics).json"
      },
      {
        "label": "Theme Flat",
        "uiTheme": "vs-dark",
        "path": "./themes/ThemeFlat.json"
      }
    ]
  }
}
```

5. Fetch the theme .json files
???

## Todo
- [x] Themes: Map vscode themes to css variable overrides
- [x] Themes: Ability to switch between available themes
- [x] Themes: Support any theme from https://vscodethemes.com/

**Comment by jeremygiberson** [comment]
Implemented in https://github.com/FormidableLabs/gui4comby/pull/20 
However, the results are not phenomenal. 

More exploration to mapping theme values to app classes may need to occur. 
<img width="792" alt="Screen Shot 2022-09-12 at 10 05 00 AM" src="https://user-images.githubusercontent.com/487411/189714108-a25f1138-8ea1-48e4-9f10-a215bba2704d.png">
